# Generated by Django 2.0 on 2020-07-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_auto_20200717_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcomemessage',
            name='service',
        ),
    ]
