# Generated by Django 2.0 on 2020-07-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_remove_outcomemessage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.CharField(default='41d92eeec90811ea91003c15c2da2c92', max_length=50),
            preserve_default=False,
        ),
    ]
